### ISSUE TITLE
Create new tag 1.0.6

### ISSUE THREAD

**Issue by elebetsamer** [ufdada/quicktable#4]
The latest commits made aren't in a release tag, so the changes made in those commits aren't making it in to the CKEditor builder or addon viewer (downloader). On the CKEditor site, version 1.0.5 is being pulled in, which is missing the ability to set the cellpadding/spacing to null etc. So it would be great to get a 1.0.6 tag in order to get the latest changes to be shown on the CKEditor site.

**Comment by ufdada** [comment]
Thanks man, didn't notice the last changes didn't got into the release version. Should be fixed with 1.0.6
