### ISSUE TITLE
Not working in inline editing mode

### ISSUE THREAD

**Issue by coolduebtn** [ufdada/quicktable#7]
The plugin does not work in inline editing mode. I see the quick table feature but on selecting and clicking it does not add the table. Is it not adapted for inline editing mode ??

**Comment by ufdada** [comment]
Sorry it took so long to reply, i was rather busy.

Just tested it in Windows 10 with IE 11, Edge and Chrome. Worked fine so far. What CKEditor version are you using and what kind of Browser?

**Comment by ufdada** [comment]
Closing because of no feedback in 2 months
